language: python
python:
  - "3.4"
  - "3.5"
  - "3.5-dev"  # 3.5 development branch
  - "3.6"
  - "3.6-dev"  # 3.6 development branch
  # - "3.7"
# command to install dependencies
install:
  - pip install isONcorrect
  # - pip install coveralls
# os:
#   - linux
#   - osx
# safelist
branches:
  only:
  - master
  # - develop
# command to run tests
script: python isONcorrect --fastq  test_data/isoncorrect/0.fastq --outfolder ~/tmp/test/ 
        python run_isoncorrect --t 3 --fastq_folder  test_data/isoncorrect/ --outfolder ~/tmp/test_parallel/ 
# after_success:
#  - coveralls